# configs/EB-Navigation.yaml
model_name: gpt-4o-mini # Qwen/Qwen2.5-VL-7B-Instruct gpt-4o-mini Qwen/Qwen2.5-72B-Instruct-Turbo
down_sample_ratio: 0.1
model_type: remote
language_only: True
eval_sets: ['base'] #  ['base', 'common_sense', 'complex_instruction', 'spatial_relationship', 'visual_appearance', 'long_horizon'] 
chat_history: False
n_shots: 10
multistep: False
resolution: 500
recording: True
exp_name: ttt
env_feedback: True
tp: 1